name: "eslint tsc test"
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: |
        yarn install
    - name: lint test
      run: |
        yarn lint
    - uses: 8398a7/action-slack@v3
    - name: lint test result
      with:
        status: ${{job.status}}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: dante01yoon
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      if: always()
